name: settings_yaml
version: 8.1.0-alpha.1
homepage: https://github.com/bsutton/settings_yaml
description: Provides a simple means of saving/loading settings from a yaml file without the yaml fuss.
repository: https://github.com/open-runtime/settings_yaml-4.x
environment: 
  sdk: '>=3.0.0 <4.0.0'
dependencies: 
  collection: ^1.18.0
  meta: ^1.12.0
  path: ^1.9.0
  uuid: ^4.3.3
  yaml: ^3.1.2
  dcli_core:
dev_dependencies:
  lint_hard: ^4.0.0
  test: ^1.25.2
